sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "node"

install:
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: 
  - npm run lint
  - npm run test:cover

after_success: npm run coveralls

cache:
  yarn: true
  